#!/usr/bin/env python3
"""Backtest an Algothon strategy over a configurable price window."""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path
from types import ModuleType
from typing import Callable

import numpy as np
import pandas as pd


ANNUALIZATION = 250
DEFAULT_TEST_DAYS = 250
DEFAULT_COMMISSION_RATE = 0.0001
INSTRUMENT_0_COMMISSION_RATE = 0.00002
DEFAULT_DOLLAR_POSITION_LIMIT = 10_000
INSTRUMENT_0_DOLLAR_POSITION_LIMIT = 100_000


def load_prices(path: Path) -> tuple[np.ndarray, list[str]]:
    """Load whitespace-delimited prices as (instruments, days)."""
    frame = pd.read_csv(path, sep=r"\s+", header=0)
    if frame.empty:
        raise ValueError(f"price file is empty: {path}")

    prices = frame.to_numpy(dtype=float).T
    if not np.isfinite(prices).all():
        raise ValueError("prices must contain only finite values")
    if (prices <= 0).any():
        raise ValueError("prices must be strictly positive")

    return prices, [str(column) for column in frame.columns]


def load_strategy(path: Path) -> ModuleType:
    """Load a strategy module from an arbitrary Python file."""
    spec = importlib.util.spec_from_file_location("backtest_strategy", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"could not load strategy from {path}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    if not callable(getattr(module, "getMyPosition", None)):
        raise AttributeError(
            f"{path} must define a callable getMyPosition(prcSoFar)"
        )

    return module


def score_2026(mu: float, sigma: float) -> float:
    """Return the Algothon 2026 risk-adjusted score."""
    if mu < 0 or sigma < 1e-10:
        return mu

    sharpe = np.sqrt(ANNUALIZATION) * mu / sigma
    return mu * (sharpe**2 / (sharpe**2 + 1.0))


def resolve_window(
    n_days: int,
    *,
    days: int,
    start_day: int | None,
    end_day: int | None,
) -> tuple[int, int]:
    """
    Resolve the inclusive range of PnL days.

    Day numbers are zero-based price-row indices. PnL for ``start_day`` is
    generated by positions selected using prices through ``start_day - 1``.
    """
    if days <= 0:
        raise ValueError("days must be positive")

    end = n_days - 1 if end_day is None else end_day
    if end < 1 or end >= n_days:
        raise ValueError(f"end_day must be between 1 and {n_days - 1}")

    start = max(1, end - days + 1) if start_day is None else start_day
    if start < 1 or start > end:
        raise ValueError(f"start_day must be between 1 and end_day ({end})")

    return start, end


def run_backtest(
    prices: np.ndarray,
    get_position: Callable[[np.ndarray], np.ndarray],
    *,
    start_day: int,
    end_day: int,
    verbose: bool = False,
) -> dict[str, object]:
    """Run the strategy and return portfolio and per-instrument results."""
    n_instruments, _ = prices.shape

    commission_rates = np.full(
        n_instruments,
        DEFAULT_COMMISSION_RATE,
        dtype=float,
    )
    commission_rates[0] = INSTRUMENT_0_COMMISSION_RATE

    dollar_limits = np.full(
        n_instruments,
        DEFAULT_DOLLAR_POSITION_LIMIT,
        dtype=float,
    )
    dollar_limits[0] = INSTRUMENT_0_DOLLAR_POSITION_LIMIT

    current_position = np.zeros(n_instruments, dtype=int)
    cash_by_instrument = np.zeros(n_instruments, dtype=float)
    value_by_instrument = np.zeros(n_instruments, dtype=float)
    pending_commission = np.zeros(n_instruments, dtype=float)
    total_dollar_volume = 0.0
    daily_pnl: list[float] = []
    daily_instrument_pnl: list[np.ndarray] = []

    # Select positions at the close immediately before the first scored day,
    # then mark PnL on every day from start_day through end_day.
    for price_day in range(start_day - 1, end_day + 1):
        history = prices[:, : price_day + 1]
        current_prices = history[:, -1]

        if price_day < end_day:
            requested = np.asarray(get_position(history), dtype=float)
            if requested.shape != (n_instruments,):
                raise ValueError(
                    "getMyPosition must return a one-dimensional array with "
                    f"{n_instruments} entries; received shape {requested.shape}"
                )
            if not np.isfinite(requested).all():
                raise ValueError("getMyPosition returned non-finite positions")

            share_limits = (dollar_limits / current_prices).astype(int)
            new_position = np.clip(
                requested,
                -share_limits,
                share_limits,
            ).astype(int)
        else:
            # Final price is a mark only, matching eval.py.
            new_position = current_position.copy()

        delta_position = new_position - current_position

        # eval.py charges the commission calculated on the preceding iteration.
        cash_by_instrument -= (
            current_prices * delta_position + pending_commission
        )

        dollar_volume = current_prices * np.abs(delta_position)
        total_dollar_volume += float(dollar_volume.sum())
        pending_commission = dollar_volume * commission_rates

        current_position = new_position
        new_value_by_instrument = (
            cash_by_instrument + current_position * current_prices
        )
        pnl_by_instrument = (
            new_value_by_instrument - value_by_instrument
        )
        value_by_instrument = new_value_by_instrument

        if price_day >= start_day:
            portfolio_pnl = float(pnl_by_instrument.sum())
            daily_pnl.append(portfolio_pnl)
            daily_instrument_pnl.append(pnl_by_instrument.copy())

            if verbose:
                print(
                    f"Day {price_day}: "
                    f"value=${value_by_instrument.sum():.2f} "
                    f"PnL=${portfolio_pnl:.2f} "
                    f"$-traded={total_dollar_volume:.0f}"
                )

    pnl = np.asarray(daily_pnl, dtype=float)
    instrument_pnl = np.vstack(daily_instrument_pnl)
    mu = float(pnl.mean())
    sigma = float(pnl.std(ddof=0))
    sharpe = (
        float(np.sqrt(ANNUALIZATION) * mu / sigma)
        if sigma > 0
        else 0.0
    )

    return {
        "daily_pnl": pnl,
        "daily_instrument_pnl": instrument_pnl,
        "instrument_total_pnl": instrument_pnl.sum(axis=0),
        "mean_pnl": mu,
        "stddev_pnl": sigma,
        "sharpe": sharpe,
        "score_2025": mu - 0.1 * sigma,
        "score_2026": score_2026(mu, sigma),
        "total_dollar_volume": total_dollar_volume,
    }


def print_instrument_ranking(
    total_pnl: np.ndarray,
    instrument_names: list[str],
    *,
    count: int = 5,
) -> None:
    """Print the best and worst instruments by total test-window PnL."""
    ranking = pd.DataFrame(
        {
            "instrument_index": np.arange(len(total_pnl)),
            "instrument_name": instrument_names,
            "total_pnl": total_pnl,
        }
    )

    count = min(count, len(ranking))
    best = ranking.nlargest(count, "total_pnl")
    worst = ranking.nsmallest(count, "total_pnl")

    print("\nTop 5 best instruments:")
    print(best.to_string(index=False, formatters={"total_pnl": "${:,.2f}".format}))

    print("\nTop 5 worst instruments:")
    print(worst.to_string(index=False, formatters={"total_pnl": "${:,.2f}".format}))


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent

    parser = argparse.ArgumentParser(
        description="Backtest an Algothon getMyPosition strategy."
    )
    parser.add_argument(
        "--prices",
        type=Path,
        default=script_dir.parent / "01-data" / "prices.txt",
        help="path to prices.txt",
    )
    parser.add_argument(
        "--strategy",
        type=Path,
        default=script_dir.parent / "03-strategy" / "strateg.py",
        help="path to the strategy Python file",
    )
    parser.add_argument(
        "--days",
        type=int,
        default=DEFAULT_TEST_DAYS,
        help="number of PnL days; default: 250",
    )
    parser.add_argument(
        "--start-day",
        type=int,
        default=None,
        help="first scored day, as a zero-based price-row index",
    )
    parser.add_argument(
        "--end-day",
        type=int,
        default=None,
        help="last scored day, inclusive; default: final dataset day",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="print daily portfolio results",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    prices, instrument_names = load_prices(args.prices)
    strategy = load_strategy(args.strategy)

    start_day, end_day = resolve_window(
        prices.shape[1],
        days=args.days,
        start_day=args.start_day,
        end_day=args.end_day,
    )

    results = run_backtest(
        prices,
        strategy.getMyPosition,
        start_day=start_day,
        end_day=end_day,
        verbose=args.verbose,
    )

    print(
        f"Backtested {prices.shape[0]} instruments over "
        f"{end_day - start_day + 1} days ({start_day} to {end_day})"
    )
    print(f"mean PnL:   ${results['mean_pnl']:,.2f}")
    print(f"stddev PnL: ${results['stddev_pnl']:,.2f}")
    print(f"score_2025: {results['score_2025']:,.2f}")
    print(f"score_2026: {results['score_2026']:,.2f}")
    print(f"Sharpe:     {results['sharpe']:,.2f}")
    print(f"$-traded:   ${results['total_dollar_volume']:,.0f}")

    print_instrument_ranking(
        results["instrument_total_pnl"],
        instrument_names,
    )


if __name__ == "__main__":
    main()
